{
	"version": 1648820197,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/fire_ball-sheet0.png",
		"images/fire_ball-sheet1.png",
		"images/fire_ball-sheet2.png",
		"images/boss_base-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/stun_b.png",
		"images/arrow-sheet0.png",
		"images/hpbar_e.png",
		"images/sprite6-sheet0.png",
		"images/boss_img-sheet0.png",
		"images/boss_img-sheet1.png",
		"images/world.png",
		"media/dragon roar 7 - quicksounds.com.m4a",
		"media/dragon roar 7 - quicksounds.com.ogg",
		"media/dragon with fire 3 - quicksounds.com (1).m4a",
		"media/dragon with fire 3 - quicksounds.com (1).ogg",
		"media/male laugh 9 - quicksounds.com.m4a",
		"media/male laugh 9 - quicksounds.com.ogg",
		"media/bowmen1.m4a",
		"media/bow_shoot.m4a",
		"media/bow_shoot.ogg",
		"media/brosok-odnoy-monetki-v-obschuyu-kuchu.ogg",
		"media/lucky shot - albis.m4a",
		"media/lucky shot - albis.ogg",
		"media/outlet - silent partner.m4a",
		"media/outlet - silent partner.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}